In [11]:
import numpy as np
import pandas as pd

In [12]:

train = pd.read_csv("../data/train_preprocessed.csv")
train_x = train.drop(["target"], axis=1)
train_y = train["target"]

test_x = pd.read_csv("../data/test_preprocessed.csv")
test_x = test_x.dropna(how="any")

In [13]:
# 時系列を追加
train_x["period"] = np.arange(0, len(train_x)) // (len(train_x) // 4)
train_x["period"] = np.clip(train_x["period"], 0, 3)
test_x["period"] = 4

train_x["period"]

0       0
1       0
2       0
3       0
4       0
       ..
9995    3
9996    3
9997    3
9998    3
9999    3
Name: period, Length: 10000, dtype: int64

In [14]:
#時系列データでのhold-out
#0~3がtrain, 4がテストとする
#trainの内、0~2を学習、3をvalidatiaonとする
is_tr = train_x['period'] < 3
is_va = train_x['period'] == 3
tr_x, va_x = train_x[is_tr], train_x[is_va]
tr_y, va_y = train_y[is_tr], train_y[is_va]

In [17]:
# 時系列に沿ったクロスバリデーション
# 1,2,3をvalidationにし、それより過去のデータを学習にする
# データが十分にあるときに有効な手法
va_period_list = [1,2,3]
for va_period in va_period_list:
    is_tr = train_x['period'] < va_period
    is_va = train_x["period"] == va_period

    tr_x, va_x = train_x[is_tr], train_x[is_va]
    tr_y, va_y = train_y[is_tr], train_y[is_va]

    print(tr_x["period"].unique())

[0]
[0 1]
[0 1 2]


In [21]:
#単純に時間で分割するケース
#0,1,2,3の内一つをvalidation, それ以外をtrainとする

In [23]:
va_period_list = [0,1,2,3]
for va_period in va_period_list:
    is_tr = train_x["period"] != va_period
    is_va = train_x["period"] == va_period

    tr_x, va_x = train_x[is_tr], train_x[is_va]
    tr_y, va_y = train_y[is_tr], train_y[is_va]

    print(tr_x["period"].unique())

[1 2 3]
[0 2 3]
[0 1 3]
[0 1 2]
