In [20]:
import pandas as pd
import numpy as np

In [21]:
train = pd.read_csv("../data/3_5/train_preprocessed_onehot.csv")
train_x = train.drop(["target"], axis=1)
train_y = train["target"]

test_x = pd.read_csv("../data/3_5/test_preprocessed_onehot.csv")

In [22]:
train

age  sex      height     weight  product_0  product_1  product_2  \
0      50    1  166.445608  65.016732          0          0          0   
1      68    0  164.334615  56.544217          1          0          0   
2      77    1  167.462917  54.242267          0          0          1   
3      17    1  177.097725  71.147762          0          0          0   
4      62    0  158.165788  65.240697          0          1          0   
...   ...  ...         ...        ...        ...        ...        ...   
9995   61    1  182.729800  73.393777          0          1          0   
9996   33    0  167.701136  75.006529          0          0          0   
9997   44    0  145.609998  47.739397          0          0          0   
9998   34    0  165.796017  57.567695          0          0          0   
9999   31    1  180.301762  71.425135          0          0          0   

      product_3  product_4  product_5  ...  medical_keyword_8  \
0             0          0          0  ...                  1   
1             0          0          0  ...                  1   
2             0          0          0  ...                  1   
3             1          0          0  ...                  1   
4             0          0          0  ...                  1   
...         ...        ...        ...  ...                ...   
9995          0          0          0  ...                  1   
9996          0          0          0  ...                  1   
9997          0          0          0  ...                  1   
9998          0          0          0  ...                  1   
9999          0          1          0  ...                  1   

      medical_keyword_9  medical_keyword_10  year  month  day  yearmonth  \
0                     0                   0  2015      2    3      24182   
1                     0                   0  2015      5    9      24185   
2                     0                   0  2016      2   13      24194   
3                     0                   0  2015      7    6      24187   
4                     1                   0  2016      9   17      24201   
...                 ...                 ...   ...    ...  ...        ...   
9995                  1                   0  2015     10   21      24190   
9996                  1                   0  2015      5   28      24185   
9997                  0                   1  2016      2   29      24194   
9998                  1                   0  2016      2   27      24194   
9999                  0                   0  2015      7    1      24187   

      medical_info_c1_nan  medical_info_c2_nan  target  
0                   False                 True       0  
1                    True                 True       0  
2                   False                 True       1  
3                   False                False       0  
4                   False                 True       1  
...                   ...                  ...     ...  
9995                False                 True       0  
9996                False                 True       0  
9997                 True                 True       0  
9998                False                 True       0  
9999                False                False       0  

[10000 rows x 60 columns]

In [23]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=4, shuffle=True, random_state=71)
tr_idx, va_idx = list(kf.split(train_x))[0]
tr_x, va_x = train_x.iloc[tr_idx], train_x.iloc[va_idx]
tr_y, va_y = train_y.iloc[tr_idx], train_y.iloc[va_idx]

In [24]:
#線形モデルの実装
from sklearn.linear_model import  LogisticRegression
from sklearn.metrics import  log_loss
from sklearn.preprocessing import  StandardScaler

In [25]:
# データのスケーリング
scaler = StandardScaler()
tr_x = scaler.fit_transform(tr_x)
va_x = scaler.transform(va_x)
test_x = scaler.transform(test_x)

In [26]:
tr_x[0]

array([ 3.66348120e-01,  8.15136432e-01,  5.90161505e-02,  3.87264368e-01,
       -4.93741931e-01, -3.36288474e-01, -5.03123078e-01, -2.03769504e-01,
       -1.43342294e-01, -2.03769504e-01, -3.34566535e-01, -2.30380075e-01,
       -3.34073581e-01,  2.99556410e+00, -2.26503017e-01,  9.10152745e-01,
       -1.58231485e+00, -4.60527151e-01, -6.99006870e-01, -1.18461574e+00,
       -9.92561002e-01, -5.79813642e-01,  1.99916705e+00, -2.34205723e-01,
       -2.53837982e-01,  4.04488703e+00, -2.43253845e-01, -2.45398708e-01,
       -2.48135296e-01, -2.35469960e-01, -2.63519381e-01, -2.51748458e-01,
       -2.47225693e-01, -2.51748458e-01, -2.55914551e-01, -2.59152333e-01,
       -2.48740278e-01, -2.54135420e-01, -2.45703933e-01, -2.52047768e-01,
       -2.45703933e-01, -4.71388463e-01,  1.44958773e-03,  4.98749685e-01,
       -1.00561577e+00, -5.01874304e-01, -2.23559836e-01, -1.38420418e-01,
        1.23329169e+00, -3.28372739e-01,  5.09773453e-01, -6.57148549e-01,
       -2.32936058e-01, -

In [27]:
# モデルの構築
model = LogisticRegression(C=1.0)
model.fit(tr_x, tr_y)

LogisticRegression()

In [28]:
va_pred = model.predict_proba(va_x)
va_pred

array([[0.97877193, 0.02122807],
       [0.94646564, 0.05353436],
       [0.90758817, 0.09241183],
       ...,
       [0.8446615 , 0.1553385 ],
       [0.77220444, 0.22779556],
       [0.9632763 , 0.0367237 ]])

In [29]:
va_y

6       1
10      0
11      0
12      0
23      1
       ..
9986    0
9988    0
9994    0
9995    0
9997    0
Name: target, Length: 2500, dtype: int64

In [30]:
score = log_loss(va_y, va_pred)
score

0.3719859624156004

In [31]:
pred = model.predict(test_x)
pred

array([1, 0, 0, ..., 0, 0, 1])